### ISSUE TITLE
About Dataset 

### ISSUE THREAD

**Issue by zhuting233** [Xiaohan-Chen/transfer-learning-fault-diagnosis-pytorch#4]
When I try to run DANN.py from s_load 0 to others, the program shows :
```
Traceback (most recent call last):
  File "C:\Users\zhuqi\Desktop\transfer-learning-fault-diagnosis-pytorch-main\DANN.py", line 380, in <module>
    trainer(args)
  File "C:\Users\zhuqi\Desktop\transfer-learning-fault-diagnosis-pytorch-main\DANN.py", line 222, in trainer
    source_trainloader, target_trainloader, target_valloader, target_testloader = loaddata(args)
  File "C:\Users\zhuqi\Desktop\transfer-learning-fault-diagnosis-pytorch-main\DANN.py", line 178, in loaddata
    target_data, target_label = CWRUloader(args, args.t_load, args.t_label_set)
  File "C:\Users\zhuqi\Desktop\transfer-learning-fault-diagnosis-pytorch-main\PreparData\CWRU.py", line 58, in CWRUloader
    dataset = CWRU(args.datadir, load, label_set, args.window, args.normalization, args.backbone, args.fft)
  File "C:\Users\zhuqi\Desktop\transfer-learning-fault-diagnosis-pytorch-main\PreparData\CWRU.py", line 33, in CWRU
    mat_data = loadmat(os.path.join(path,str(fault_type)+".mat"))[realaxis]
KeyError: 'X174_DE_time'
```
I redownload the 174.mat from https://engineering.case.edu/sites/default/files/174.mat and debug the program, I found the column name is 'X173_DE'. So I rename the file 173.mat, and the lables of each class is [238, 238, 239, 237, 62, 243, 239, 238, 238, 240].  It only has 62 samples in class 4 . It 's different to other file. 
I am confused and don't know how to solve the proble. Thanks for your help.

**Comment by Xiaohan-Chen** [comment]
Hi zhuting,
Thanks for your interest in our repository.
Your operation of renaming the file `174.mat` to `173.mat` is correct, as the keys of file `174.mat` are "X173_DE_time" and "X173_FE_time". Actually, the CWRU website does not provide `173.mat` (see #3 ). Therefore, you need to download the `174.mat` and rename it to `173.mat`. In this way, the code will run correctly without errors.
Regarding the problem of the sample number of class 4 being less than the other classes, this is because the `174/173.mat` only contains about 60 000 points, but other files have over 200 000 points. You might consider reducing the samples of the other files to bring them into balance.
I hope these have addressed your confusion.

**Comment by zhuting233** [comment]
Thanks a lot! I find there may be a bug in utils.py :56 . test = torch.utils.data.TensorDataset(label_test, label_test) data_val  . I think the correct code is: test = torch.utils.data.TensorDataset(data_test, label_test) .

**Comment by Xiaohan-Chen** [comment]
> Thanks a lot! I find there may be a bug in utils.py :56 . test = torch.utils.data.TensorDataset(label_test, label_test) data_val . I think the correct code is: test = torch.utils.data.TensorDataset(data_test, label_test) .

Thanks for finding this bug, I have fixed it in the latest version of this repository. And you are also acknowledged for contributing to this repository at the bottle of the README.
